export const RecipeSchema = {
  name: 'Recipe',
  primaryKey: 'idMeal',
  properties: {
    idMeal: 'string',
    strMeal: { type: 'string', default: '' },
    strCategory: { type: 'string', default: '' },
    strInstructions: { type: 'string', default: '' },
    strMealThumb: { type: 'string', default: '' },
    strIngredient1: { type: 'string', default: '' },
    strIngredient2: { type: 'string', default: '' },
    strIngredient3: { type: 'string', default: '' },
    strIngredient4: { type: 'string', default: '' },
    strIngredient5: { type: 'string', default: '' },
    strIngredient6: { type: 'string', default: '' },
    strIngredient7: { type: 'string', default: '' },
    strIngredient8: { type: 'string', default: '' },
    strIngredient9: { type: 'string', default: '' },
    strIngredient10: { type: 'string', default: '' },
    strIngredient11: { type: 'string', default: '' },
    strIngredient12: { type: 'string', default: '' },
    strIngredient13: { type: 'string', default: '' },
    strIngredient14: { type: 'string', default: '' },
    strIngredient15: { type: 'string', default: '' },
    strIngredient16: { type: 'string', default: '' },
    strIngredient17: { type: 'string', default: '' },
    strIngredient18: { type: 'string', default: '' },
    strIngredient19: { type: 'string', default: '' },
    strIngredient20: { type: 'string', default: '' },
    strMeasure1: { type: 'string', default: '' },
    strMeasure2: { type: 'string', default: '' },
    strMeasure3: { type: 'string', default: '' },
    strMeasure4: { type: 'string', default: '' },
    strMeasure5: { type: 'string', default: '' },
    strMeasure6: { type: 'string', default: '' },
    strMeasure7: { type: 'string', default: '' },
    strMeasure8: { type: 'string', default: '' },
    strMeasure9: { type: 'string', default: '' },
    strMeasure10: { type: 'string', default: '' },
    strMeasure11: { type: 'string', default: '' },
    strMeasure12: { type: 'string', default: '' },
    strMeasure13: { type: 'string', default: '' },
    strMeasure14: { type: 'string', default: '' },
    strMeasure15: { type: 'string', default: '' },
    strMeasure16: { type: 'string', default: '' },
    strMeasure17: { type: 'string', default: '' },
    strMeasure18: { type: 'string', default: '' },
    strMeasure19: { type: 'string', default: '' },
    strMeasure20: { type: 'string', default: '' },
  },
};
